Выполнены основные задачи 10-го спринта
Yapinkis/java-filmorate pull request #1
Opened 2024-07-22 09:27 UTC by Yapinkis

2024-07-22 10:13 UTC, Yapinkis commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTests.java
> +	void filmNameCannotBeNull() {
По какой-то причине CheckStyle в ide у меня не отработал ошибки, а они появились только на этапе отправки проекта в гит. Из-за чего это может быть? Файлик с чекстайлом перезагрузил, но ошибок всё-равно не было

2024-07-24 08:31 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTests.java
> +	void filmNameCannotBeNull() {
у идеи есть всякие кэши, и частенько они могут отрабатывать не совсем удобно, 
обычно в случае каких то проблем с идеей самое первое что делают - инвалидируют их
![image](https://github.com/user-attachments/assets/243f9e2e-731e-4739-a59b-a53bc62fe43e)

2024-07-24 09:36 UTC, TomattmanYandex requested changes
Комменты в коде

2024-07-24 09:36 UTC, TomattmanYandex commented on pom.xml
> +		<dependency>
ДЛя большинства самых распространённых задач уже есть готовые библиотеки, и у спринга их много, под самые разные задачи, которые  отлично с ним взаимодействуют
и обычно если что то надо сделать гораздо проще поискать уже готовую библиотеку и ее переиспользовать 
например
<dependency> 
    <groupId>org.springframework.boot</groupId> 
    <artifactId>spring-boot-starter-validation</artifactId> 
</dependency>

Второй момент про зависимости,
скорее всего у библиотеки которую ты добавляешь, есть другие зависимости, например у спринга уже есть зависимость от библиотек с логгерами, и когда ты добавляешь или другие библиотеки, или тут же библиотеку но другой версии, могут быть конфликты, поэтому рекомендую использовать то что уже есть

2024-07-24 09:36 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	//Я не могу понять, почему у меня в Postman на одной машине проходятся все тесты, а при поптыке пройти их на
без дебага понять сложно, возможно что то режется системой, и не хватает полей
но вообще ситуация странная, в первую очередь стоит проверить что на разных машинах запускается одна и та же версия

2024-07-24 09:36 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmorateManager filmorateManager = new FilmorateManager();
модификаторы доступа

2024-07-24 09:36 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmorateManager filmorateManager = new FilmorateManager();
если делаешь отдельным классом сам менеджер, то почитай про аннотацию Component и инжект зависимостей в спринге

2024-07-24 09:36 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    // Создаются ли для контроллеров интерфейсы? Просто я бы мог создать три метода: add, update и get и уже их
обычно нет
так как не всегда тебе будет нужны все три метода

для контроллеров иногда делают интерфейсы, но больше для документации
есть инструменты позволяющие сгенерировать документацию автоматически, и для них есть множество аннотаций, и для того чтобы не перегружать код самого контроллера этими аннотациями, делают интерфейс (под каждый отдельный контроллер) и в нем на методы вещают все эти аннотации для документации, а в основном классе оставляют только логику

2024-07-24 09:36 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    // Jakarta Bean Validation наверное то же имеет смысл импортировать в проект
про это я написал в комментариях помки

2024-07-24 09:36 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (filmorateManager.validateFilm(film)) {
есть хороший способ как по другому это заимплементить
даже два, в зависимости от предпочтений
1) не стоит бояться использовать и пробрасывать исключения, спринг с ними хорошо работает, 
сделать так чтобы метод vallidateFilm в случае ошибки пробрасывал исключение, и все, уже не надо никакого ветвления, ошибка есть, отливится спрингом где то выше (можно и даже нужно написать обработчик ошибок который будет обрабатывать ошибку и возвращать красивый ответ. Гуглить restcontrolleradvice)
2) этот способ похож на текущую реализацию, но повышает читаемость и красоту кода
в начале проверяем неправильные значения, и если они неправильны, кидаем ошибку и выходим из метода, потом выполняем основные дествия
if(!isFilmValid(film)){
return null;
}
film.setId(filmorateManager.nextFilmId());
films.put(film.getId(), film);

2024-07-24 09:36 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (filmorateManager.validateFilm(film)) {
так же рекомендую сделать валидацию аннотациями

2024-07-24 09:36 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (filmorateManager.validateFilm(film)) {
и еще момент,  не понимаю почему тесты не свалились
если валидация не прошла, и мы не добавили фильм в хранилище, должны возвращаться ошибка а не сам обьект

2024-07-24 09:36 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            filmorateManager.validateUpdateFilm(updatedFilm);
1) можно сначала провалидировать то что пришло
2) джава работает с памятью так, что даже если валидация не пройдет, поля все равно будут изменены
3) как я писал выше, следует сделать хендлер ошибок, и не отлавливать тут ошибку
4) не стоит возвращать фильм, если выполнилось с ошибкой

2024-07-24 09:36 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    FilmorateManager filmorateManager = new FilmorateManager();
тут комментарии будут такие же как и в контроллере фильмов

2024-07-24 09:36 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/exception/UpdateException.java
> +public class UpdateException extends RuntimeException {
лучше делать ошибки с более понятными именами и более специфическими
не понятно что значит UpdateException 
тут кажется больше подойдет EntityNotFoundException

2024-07-24 09:36 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +// Наверное нам здесь не нужен конструктор без параметров.
иногда удобно иметь конструктор без параметров, просто потому что нужно иметь пустую сущность
многие библиотеки требуют чтобы был конструктор без параметров

есть разные случаи

2024-07-24 09:36 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NonNull //Нужна ли здесь эта аннотация, если я использую выброс пользовательского исключения?И если да, то может
эта аннотация не будет работать пока ты где то не повесишь аннотацию @Valid Например на параметр контроллера
и да рекомендую сделать валидацию через аннотации

2024-07-24 09:36 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NonNull //Нужна ли здесь эта аннотация, если я использую выброс пользовательского исключения?И если да, то может
перепутал, посмотрел импорты, это немного не та аннотация
с этой аннотацией да, ты не позволишь чтобы в переменной был null 
и это уже зависит от дизайна прилоложения, но она сработает и когда ты попытаешься засетать Null значение и выкинет другую ошибку

2024-07-24 09:36 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    //Можно же использовать Long или тип данных обязательно должен быть Duration?
как тебе удобнее, с Long будет попроще

2024-07-24 09:36 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Integer id;
обычно для идентификаторов используют Long

2024-07-24 09:36 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/MappingManager.java
> +    //имеет ли смысл делать обобщенные методы по типу <T> boolean validate(T object)
Я вообще не вижу смысла в этом интерфейсе и классе наследнике
обычно для каждого типа объекта есть свой сервис в котором проходит вся логика касательно этого объекта
валидацию чаще всего или делают аннотациями, или помещают на уровне контроллера, счетчики идентификаторов, вообще на уровне базы данных, пока что рекомендую убрать эти классы, и сделать все на уровне контроллера, ну или сделать раздельные сервисы, но тогда мапу с данными хранить тоже на уровне сервиса

2024-07-24 09:36 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/MappingManager.java
> +    //а далее в реализации через instanceof производить каст объекта? Или лучше сразу написать несколько реализаций
instanceof стараемся не использовать, вместо этого есть перегрузка методов и строго обозначенные типы

2024-07-24 09:36 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmorateManager.java
> +public class FilmorateManager implements MappingManager {
по этому классу написал коммент в интерфейсе

2024-07-24 09:36 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            Film updatedFilm = films.get(film.getId());
что будет если фильм не найден

2024-07-24 09:36 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTests.java
> +	private Film film;
плохой стиль когда у тебя есть переменная нужная только в методе выносить ее на уровень класса
если тебе надо будет несколько раз использовать это значение, лучше сделай метод, который будет возвращать Film

2024-07-24 09:36 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTests.java
> +	@DisplayName("Добавление фильма с описанием более 200 символов")
по тестам
1) хорошее имя тестового метода
обычно состоит из трех частей
название тестируемого метода, что должно произойти, при каких условиях
последняя часть опциональна
например
validateFilm_throwValidationException_descriptionLongerThan200
разделяют их или нижними подчеркиваниями или словами should when 
нижние подчеркивания нагляднее
2) структура метода
хороший тетсовый метод можно разделить на три части, которые часто разделяют коментариями
//given
тут подготовка входных данных
//that
тут вызов тестируемого метода
//then
тут проверки

как раз согласно этой структуре не стоит выносить методы на уровень класса, чтобы было понятно откуда что берется

2024-08-03 11:58 UTC, Yapinkis commented on src/main/java/ru/yandex/practicum/filmorate/service/MappingManager.java
> +
![КакБытьКакЖить](https://github.com/user-attachments/assets/ca0236e4-fd5c-467b-b7b0-15652297a29c)

исходил из этого

2024-08-03 12:01 UTC, Yapinkis commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTests.java
> +	}
![КакБытьКакЖить2](https://github.com/user-attachments/assets/75ac85a9-dc26-40ce-8b3f-74c37a06b756)

был просто такой пример в теории.Я и подумал, что лучше создавать тестовый объект каждый раз перед запуском теста с предустановленными параметрами

2024-08-05 07:18 UTC, tomattman approved these changes
Привет, есть пара мелочей, они не критичные, но лучше их поправить, к следующей работе
Принято

2024-08-05 07:18 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmorateManager filmorateManager) {
так как вы используете lombook то для инжекта зависимостей есть более удобный способ, все зависимости делаешь private final и на класс вешаешь аннотацию @RequiredArgsConstructor и она автоматически создаст конструктор, это гораздо удобнее в плане поддержки, ведь если появятся еще зависимости, то не придётся изменять существующий конструктор

2024-08-05 07:18 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmorateManager.java
> +    public boolean validateFilm(Film film) {
я бы порекомендовал сделать или пробрасывание ошибок или возвращаемое значение, ибо не имеет смыла сделать сразу и то и другое
лучше ошибками
если хочешь сделать чтобы возвращался boolean то лучше сделать имя isFilmValid

2024-08-05 07:18 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/MappingManager.java
> +
тогда стоит назвать его ValidationManager
но вообще стандартно под каждый тип сущностей используется отдельный сервис, но это будет более актуально в следующем спринте

2024-08-05 07:18 UTC, tomattman commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTests.java
> +	}
тут можено смотреть с двух сторон, со стороны тестируемого обьекта
это создавать в beforeEach каждый раз новый FilmorateManager
это удобно и хорошо, потому что как каждый раз будет пустой контейнер перед запуском

а вот наполнять его я все же рекомендую в самом тестовом методе, просто для наглядности и понятности
а то иногда бывают тестовые методы типа
public void getAll_returnAllValues(){
   assertEquals(3, service.getAll().size())
} //пример максимально абстрактный
и когда читаешь этот метод, то не очень понятно откуда вообще что-то появилось, и почему оно должно быть этого размера, а если наполнять первым действием, внутри метода, то да оно выглядит чуть массивнее, с дупликацией кода, но при этом сразу все понятно, что и откуда взялось

2024-08-14 09:34 UTC, tomattman approved these changes

2024-08-14 10:08 UTC, merged